name: pixelmatch
description: Simple diff pixel image comparison library
version: 1.0.0
repository: https://github.com/munrocket/pixelmatch

environment:
  sdk: ^3.6.0-334.4.beta

dev_dependencies:
  image: ^4.3.0
  lints: ^5.0.0
  test: ^1.24.0
