name: CI

on: 
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: dart pub get
      - name: == Dart testing ==
        run: dart test test/dart_test.dart --reporter=github
      - name: == Flutter testing ==
        run: flutter test test/integration_test.dart --reporter=github