name: CI

on: 
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup dart sdk
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Get dependencies
        run: dart pub get

      - name: === LINT TESTING ===
        run: dart analyze
        continue-on-error: true

      - name: === UNIT TESTING ===
        run: dart test --reporter=github